version: '3'
services:
  frontend:
    build:
      context: ./frontend_appsilon
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend_appsilon
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DB_URL=postgresql://postgres:postgres@database:5432/appsilon_db

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
